### ISSUE TITLE
Online Demo Not Working

### ISSUE THREAD

**Issue by mrudu** [meyerphi/strix#5]
Online Demo does not seem to provide the display of the synthesized mealy machine anymore.

**Comment by meyerphi** [comment]
Unfortunately, the online demo has been deactivated due to insufficient resources for maintenance. I did not communicate this clearly before, leading to the broken state you observed. Now I have changed the [entry site of the demo](https://meyerphi.github.io/strix-demo/) to show a disclaimer.
