### ISSUE TITLE
Assertion failure in ZLK solver

### ISSUE THREAD

**Issue by eliyaoo32** [meyerphi/strix#7]
**Description:**
When trying to run Strix with the following configuration: `solver=ZLK  exploration=BSF output=aag`, which is the winning configuration in the SYNTCOMP).
The assertion `assert!(!compute_strategy)` in the file [zlk.rs](https://github.com/meyerphi/strix/blob/c0b1298fe2e0d46325662b89cb58a19cb4f02be5/src/parity/solver/zlk.rs#L88) fails.

**Produce Steps:**
Example of CLI running (Benchmark [ltl2dpa04](https://github.com/SYNTCOMP/benchmarks/blob/0ba61be5dec95cbe54f5937cb568547ae1ec14b5/tlsf/ltl2dpa/ltl2dpa04.tlsf)):
```
strix -f "((G ((p0) <-> (! (p1)))) && ((F ((a) && (b))) <-> (G (F (p0)))))" --ins="b,a" --outs="p1,p0" -o aag -e bfs --solver zlk
```

Output (with RUST_BACKTRACE=full):
```
thread 'main' panicked at 'assertion failed: !compute_strategy', src/parity/solver/zlk.rs:88:9
stack backtrace:
   0:     0x55f59c464bcd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h941ee1421d11073a
   1:     0x55f59c4244be - core::fmt::write::h2f422cb945c805a2
   2:     0x55f59c44ef54 - std::io::Write::write_fmt::h8f9d0365ac9506ac
   3:     0x55f59c451c24 - std::panicking::default_hook::{{closure}}::hbe1e3ca4f89cf8c0
   4:     0x55f59c4524a9 - std::panicking::rust_panic_with_hook::he1ec1558452e9d0b
   5:     0x55f59c464fab - std::panicking::begin_panic_handler::{{closure}}::h649428e396ec4455
   6:     0x55f59c464f46 - std::sys_common::backtrace::__rust_end_short_backtrace::h93616e22db15c924
   7:     0x55f59c451e52 - rust_begin_unwind
   8:     0x55f59c3bdce2 - core::panicking::panic_fmt::hd4a6277baa7a1fdc
   9:     0x55f59c3bdcac - core::panicking::panic::h0f4d8ccc452c22f3
  10:     0x55f59c480d35 - <strix::parity::solver::incremental::IncrementalSolver<S> as strix::parity::solver::incremental::IncrementalParityGameSolver>::strategy::h3cd37be1d6b602af
  11:     0x55f59c46f795 - strix::synthesize_with::he068b0e33b706938
  12:     0x55f59c3d5744 - strix::main::h64dfa4b5a95bd6a9
  13:     0x55f59c3d9d73 - std::sys_common::backtrace::__rust_begin_short_backtrace::he65005995cea8b77
  14:     0x55f59c3dd224 - main
  15:     0x7f413c9d9d85 - __libc_start_main
  16:     0x55f59c3c923e - _start
  17:                0x0 - <unknown>
```

**Environment:**
Strix version: Built from commit c0b1298fe2e0d46325662b89cb58a19cb4f02be5 (The latest commit)
Rust Version: 1.60.0
OS: Rocky Linux 8.6

**Comment by meyerphi** [comment]
Strategy computation with Zielonka's algorithm was never implemented in Strix, which the assert guards against. Also see the TODO above the assert. So the combination of ZLK solver with AAG output is not supported.

I believe Strix never ran with Zielonka's algorithm in the SYNTHESIS track, only in the REALIZABILITY track. And the decision problem is supported with this algorithm.

**Comment by eliyaoo32** [comment]
I see, By the SYNTCOMP 2023 [results](http://www.syntcomp.org/syntcomp-2023-results/) , it reports that highest scored LTL Synthesis tool is Strix  in zlk + bfs.
Here's a screenshot:

![image](https://github.com/meyerphi/strix/assets/6465846/f1dfef9b-fb93-4932-93f8-c68c8189322d)

**Comment by meyerphi** [comment]
I see, thanks for the information. I didn't even know that Strix entered the competition this year, I think it was entered by the organizers with one of the configurations from the last years.

If you download the `ltl_synth_zlk_pq` configuration and Strix itself from StarExec, however you can see that Strix is not actually called with the ZLK solver argument, but rather invoked as follows:
```
./strix -f "$LTL" --ins "$INS" --outs "$OUTS" --aiger --lookahead=0 --exploration bfs
```
And this causes Strix to use the default FPI solver. So there is a mislabeling of the configuration in the competition.

**Comment by eliyaoo32** [comment]
I see, thank you :)
